name: Deploy Project
on: 
    push:
        branches:
            - main
jobs:
    test:
      env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      runs-on: ubuntu-latest
      steps:
          - name: Get code
            uses: actions/checkout@v4
          - name: Install Node JS
            uses: actions/setup-node@v3
            with:
              node-version: 18
          - name: Install dependencies
            run: npm ci
            working-directory: ./sample-react-project-01
          - name: Test code
            id: run-tests
            run: npm run test
            working-directory: ./sample-react-project-01
          - name: Uploading Test Report
            if: failure() && steps.run-tests.outcome == 'failure'
            uses: actions/upload-artifact@v3
            with:
              name: test-report
              path: ./sample-react-project-01/test.json
          - name: Print env variables
            run: echo "Printing env variables ${{env.DB_USERNAME}}"
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Getcode
              uses: actions/checkout@v4
            - name: Install Node JS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
              working-directory: ./sample-react-project-01
            - name: Build Project
              run: npm run build
              working-directory: ./sample-react-project-01
            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                name: dist-files
                path: ./sample-react-project-01/dist
            - name: Deploy
              run: echo "Deploying..."
              working-directory: ./sample-react-project-01
            - name: Print Environment Variables
              run: |
                echo "Print Github Actor env variable : ${{github.actor}}"